# Form implementation generated from reading ui file 'tabedit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TabEdit(object):
    def setupUi(self, TabEdit):
        TabEdit.setObjectName("TabEdit")
        TabEdit.resize(400, 300)
        TabEdit.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(TabEdit)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=TabEdit)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.toolButton = QtWidgets.QToolButton(parent=self.frame)
        self.toolButton.setGeometry(QtCore.QRect(20, 4, 32, 32))
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(parent=self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(60, 4, 32, 32))
        self.toolButton_2.setText("")
        self.toolButton_2.setObjectName("toolButton_2")
        self.tbAdd = QtWidgets.QToolButton(parent=self.frame)
        self.tbAdd.setGeometry(QtCore.QRect(100, 4, 32, 32))
        self.tbAdd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/add.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbAdd.setIcon(icon)
        self.tbAdd.setObjectName("tbAdd")
        self.tbDel = QtWidgets.QToolButton(parent=self.frame)
        self.tbDel.setGeometry(QtCore.QRect(140, 4, 32, 32))
        self.tbDel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/delete.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbDel.setIcon(icon1)
        self.tbDel.setObjectName("tbDel")
        self.tbSubmit = QtWidgets.QToolButton(parent=self.frame)
        self.tbSubmit.setGeometry(QtCore.QRect(180, 4, 32, 32))
        self.tbSubmit.setText("")
        self.tbSubmit.setObjectName("tbSubmit")
        self.tbRevert = QtWidgets.QToolButton(parent=self.frame)
        self.tbRevert.setGeometry(QtCore.QRect(220, 4, 32, 32))
        self.tbRevert.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/revert.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbRevert.setIcon(icon2)
        self.tbRevert.setObjectName("tbRevert")
        self.verticalLayout.addWidget(self.frame)
        self.tableView = QtWidgets.QTableView(parent=TabEdit)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=TabEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TabEdit)
        self.buttonBox.accepted.connect(TabEdit.accept) # type: ignore
        self.buttonBox.rejected.connect(TabEdit.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TabEdit)

    def retranslateUi(self, TabEdit):
        _translate = QtCore.QCoreApplication.translate
        self.tbAdd.setToolTip(_translate("TabEdit", "<html><head/><body><p>Add record to table</p></body></html>"))
        self.tbDel.setToolTip(_translate("TabEdit", "<html><head/><body><p>Delete record from table</p></body></html>"))
        self.tbSubmit.setToolTip(_translate("TabEdit", "<html><head/><body><p>Submit changes</p></body></html>"))
        self.tbRevert.setToolTip(_translate("TabEdit", "<html><head/><body><p>Revert changes</p></body></html>"))
