
BEGIN TRANSACTION;
DROP TABLE IF EXISTS typew;
CREATE TABLE typew (id INTEGER CONSTRAINT id PRIMARY KEY AUTOINCREMENT, name VARCHAR(256), note TEXT);

DROP TABLE IF EXISTS workout;
CREATE TABLE workout (id INTEGER CONSTRAINT id PRIMARY KEY AUTOINCREMENT, typew_id INTEGER NOT NULL, datew DATE, dist NUMERIC, note TEXT, FOREIGN KEY (typew_id) REFERENCES typew(id));
END TRANSACTION;